apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-app-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: todo-app-svc
            port:
              number: 1234
      - pathType: Prefix
        path: "/pingapi"
        backend:
          service:
            name: pingpong-app-svc
            port:
              number: 3456
      - pathType: Prefix
        path: "/todoapi"
        backend:
          service:
            name: todo-app-svc
            port:
              number: 2345
        
