apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingpong-postgres
spec:
  serviceName: pingpong-postgres
  replicas: 1
  selector:
    matchLabels:
      app: pingpong-postgres
  template:
    metadata:
      namespace: todo-namespace
      labels:
        app: pingpong-postgres
    spec:
      containers:
        - name: pingpong-postgres
          image: postgres
          volumeMounts:
            - name: pingpong-data              
              mountPath: /var/lib/postgresql/data
          ports:
            - containerPort: 5432
          
              name: web           
          environment:
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: todo-app-variables
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-namespace-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: todo-app-variables
                  key: POSTGRES_DB
            - name: PGDATA
              valueFrom:
                configMapKeyRef:
                  name: todo-app-variables
                  key: PGDATA
  volumeClaimTemplates:
    - metadata:
        name: pingpong-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi