apiVersion: v1 # Includes the Service for lazyness
kind: Service
metadata:
  name: todo-postgres
  namespace: todo-namespace
spec:
  ports:
  - port: 5432
    name: web
  clusterIP: None
  selector:
    app: todo-postgres