apiVersion: v1 # Includes the Service for lazyness
kind: Service
metadata:
  name: todo-mongo-svc
  namespace: todo-namespace
spec:
  ports:
  - port: 27017
    name: web
    targetPort: 27017
  clusterIP: None
  selector:
    app: todo-mongo