apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: data-claim
      containers:
        - name: log-output-writer
          image: koskinentht/log-output-writer:v0.7
          volumeMounts:
          - name: shared-data
            mountPath: /usr/src/app/files
        - name: log-output-reader
          image: koskinentht/log-output-reader:v0.7
          volumeMounts:
          - name: shared-data
            mountPath: /usr/src/app/files
          