apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: log-output-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: log-output-svc
            port: 
              number: 2345
      - pathType: Prefix
        path: "/pingpong"
        backend:
          service:
            name: pingpong-app-svc
            port:
              number: 3456
        
