apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: todo-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      namespace: todo-namespace
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: data-claim
      containers:
        - name: todo-back
          image: koskinentht/todo-back:v1.0
          imagePullPolicy: "Always"
          volumeMounts:
          - name: shared-data
            mountPath: /usr/src/app/files

        - name: todo-front
          image: koskinentht/todo-front:v1.1
          imagePullPolicy: "Always"
          env:
            - name: REACT_APP_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: todo-app-variables
                  key: MESSAGE
          
        - name: todo-timestamp
          image: koskinentht/todo-timestamp:v1.0
          imagePullPolicy: "Always"
          volumeMounts:
          - name: shared-data
            mountPath: /usr/src/app/files