apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: data-claim
      containers:
        - name: todo-back
          image: koskinentht/todo-back:v1.0
          volumeMounts:
          - name: shared-data
            mountPath: /usr/src/app/files

        - name: todo-front
          image: koskinentht/todo-front:v1.0
          
        - name: todo-timestamp
          image: koskinentht/todo-timestamp:v1.0
          volumeMounts:
          - name: shared-data
            mountPath: /usr/src/app/files