apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc
spec:
  type: ClusterIP
  selector:
    app: todo-app
  ports:
  - name: todo-front
    port: 1234
    protocol: TCP
    targetPort: 3000
  - name: todo-back
    port: 2345
    protocol: TCP
    targetPort: 3002
  