apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong-app
  template:
    metadata:
      labels:
        app: pingpong-app
    spec:
#      volumes:
#        - name: shared-visits
#          persistentVolumeClaim:
#            claimName: data-claim
      containers:
        - name: pingpong-app
          image: koskinentht/pingpong-app:v0.3
#          volumeMounts:
#          - name: shared-visits
#            mountPath: /usr/src/app/files