apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-app-dep
  # namespace: todo-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong-app
  template:
    metadata:
      # namespace: todo-namespace
      labels:
        app: pingpong-app
    spec:
      containers:
        - name: pingpong-app
          image: koskinentht/pingpong-app:v1.2
          imagePullPolicy: "Always"          
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: todo-app-variables
                  key: PING_POSTGRES_HOST
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: todo-app-variables
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-namespace-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: todo-app-variables
                  key: POSTGRES_DB