apiVersion: v1
kind: Service
metadata:
  name: pingpong-app-svc
spec:
  type: ClusterIP
  selector:
    app: pingpong-app
  ports:
  - name: pingpong-http    
    protocol: TCP
    port: 3456
    targetPort: 3002
