apiVersion: v1
kind: Service
metadata:
  name: pingpong-app-svc
  # namespace: todo-namespace
spec:
  type: LoadBalancer
  selector:
    app: pingpong-app
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3001
