apiVersion: v1
kind: Service
metadata:
  name: pingpong-app-svc
  namespace: todo-namespace
spec:
  type: ClusterIP
  selector:
    app: pingpong-app
  ports:
  - port: 3456
    protocol: TCP
    targetPort: 3001
