apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput-app-dep
  namespace: todo-namespace
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: logoutput-app
  template:
    metadata:
      labels:
        app: logoutput-app
    spec:
      volumes:
      - name: shared-visits
        persistentVolumeClaim:
          claimName: data-claim
      containers:
        - name: logoutput-app
          image: koskinentht/logoutput-app:v1.0
          imagePullPolicy: "Always"
          volumeMounts:
          - name: shared-visits
            mountPath: /usr/src/app/files