apiVersion: v1
kind: Service
metadata:
  name: logoutput-app-svc
  namespace: todo-namespace
spec:
  type: ClusterIP
  selector:
    app: logoutput-app
  ports:
  - port: 4567
    protocol: TCP
    targetPort: 3003
